language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    
script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-bookstore *
  - mkdir -p deploy
  - mv springboot-bookstore.zip deploy/springboot-bookstore.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-bookstore
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifiactions:
  email:
    recipients:
      - z7942s@naver.com
